name: CI

on: [pull_request, push, workflow_dispatch]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  repository:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prettier
        run: npm install -g prettier && prettier --check '**/*.yml'

      - uses: gaurav-nelson/github-action-markdown-link-check@v1

      - name: Format README
        run: |
          cargo install cargo-readme
          ./scripts/update_readme.sh && git diff --exit-code

  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: [".", "lint"]

    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - uses: actions/checkout@v2

      - name: Features
        if: ${{ matrix.dir == '.' }}
        run: echo 'FEATURES=--features=camino' >> $GITHUB_ENV

      - name: Install dylint-link
        run: cargo install dylint-link

      - name: Cargo sort
        run: |
          cargo install cargo-sort
          cargo sort --check --grouped

      - name: Format
        run: |
          rustup component add rustfmt
          cargo fmt && git diff --exit-code

      - name: License
        run: |
          cargo install cargo-license
          cargo license | while read X; do echo "$X" | grep -w 'Apache\|CC0\|ISC\|MIT\|N/A'; done

      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy $FEATURES -- -D warnings -W clippy::pedantic

      - name: Test
        run: |
          cargo test $FEATURES

      - name: Test documentation
        # smoelius: The `cdylib` -> `lib` trick is due to @MinerSebas.
        run: |
          sed -i 's/"cdylib"/"lib"/g' Cargo.toml
          cargo test --doc

      - name: Udeps
        run: |
          # smoelius: The `rust-toolchain` file can interfere with the installation of `cargo-udeps`.
          cargo +stable install cargo-udeps
          TOOLCHAIN=
          if [[ '${{ matrix.dir }}' = '.' ]]; then
            rustup toolchain install nightly
            TOOLCHAIN='+nightly'
          fi
          cargo clean && cargo $TOOLCHAIN udeps --tests $FEATURES
